# Generated by Django 4.1.5 on 2023-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('email', models.CharField(default='rr21phe0016@student.nitw.ac.in', max_length=40)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('Chemical', 'Chemical Engineering'), ('Civil', 'Civil Engineering'), ('MME', 'Metallurgical and Materials Engineering'), ('Biotech', 'Biotechnology'), ('IMSC', 'Integrated Msc')], max_length=50)),
                ('semester', models.CharField(choices=[('1st', '1st Sem'), ('2nd', '2nd Sem'), ('3rd', '3rd Sem'), ('4th', '4th Sem'), ('5th', '5th Sem'), ('6th', '6th Sem'), ('7th', '7th Sem'), ('8th', '8th Sem')], max_length=50)),
                ('exam_type', models.CharField(choices=[('Minor-1', 'Minor-1'), ('Mid Sem', 'Mid Sem'), ('Minor-2', 'Minor-2'), ('End Sem', 'End Sem')], default='Minor-1', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='Question-Papers')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('token', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
